/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Project {
  'id' : bigint,
  'status' : ProjectStatus,
  'topic' : string,
  'owner' : Principal,
  'scenes' : [] | [Array<Scene>],
  'goal' : ProjectGoal,
  'customScript' : [] | [string],
  'script' : [] | [Script],
  'createdAt' : bigint,
  'voiceoverType' : VoiceoverType,
  'audience' : ProjectAudience,
  'platform' : ProjectPlatform,
  'style' : ProjectStyle,
}
export type ProjectAudience = { 'professionals' : null } |
  { 'students' : null } |
  { 'beginners' : null };
export type ProjectGoal = { 'educate' : null } |
  { 'explain' : null } |
  { 'sell' : null } |
  { 'inspire' : null };
export interface ProjectInput {
  'topic' : string,
  'goal' : ProjectGoal,
  'voiceoverType' : VoiceoverType,
  'audience' : ProjectAudience,
  'platform' : ProjectPlatform,
  'style' : ProjectStyle,
}
export type ProjectPlatform = { 'tiktok' : null } |
  { 'youtube' : null };
export type ProjectStatus = { 'scenes_ready' : null } |
  { 'scripted' : null } |
  { 'complete' : null } |
  { 'rendering' : null } |
  { 'draft' : null };
export type ProjectStyle = { 'social' : null } |
  { 'minimal' : null } |
  { 'cinematic' : null } |
  { 'threeD' : null };
export interface Scene {
  'title' : string,
  'duration' : bigint,
  'voiceoverLine' : string,
  'visualDescription' : string,
  'index' : bigint,
}
export interface Script {
  'cta' : string,
  'value' : string,
  'patternInterrupt' : string,
  'hook' : string,
  'main' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VoiceoverType = { 'custom' : null } |
  { 'auto' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<[ProjectInput], bigint>,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'generateScenes' : ActorMethod<[bigint], string>,
  'generateScript' : ActorMethod<[bigint], string>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProject' : ActorMethod<[bigint], Project>,
  'getProjectCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProjects' : ActorMethod<[], Array<Project>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCustomScript' : ActorMethod<[bigint, string], undefined>,
  'updateProjectScenes' : ActorMethod<[bigint, Array<Scene>], undefined>,
  'updateProjectScript' : ActorMethod<[bigint, Script], undefined>,
  'updateProjectStatus' : ActorMethod<[bigint, ProjectStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];