/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProjectGoal = IDL.Variant({
  'educate' : IDL.Null,
  'explain' : IDL.Null,
  'sell' : IDL.Null,
  'inspire' : IDL.Null,
});
export const VoiceoverType = IDL.Variant({
  'custom' : IDL.Null,
  'auto' : IDL.Null,
});
export const ProjectAudience = IDL.Variant({
  'professionals' : IDL.Null,
  'students' : IDL.Null,
  'beginners' : IDL.Null,
});
export const ProjectPlatform = IDL.Variant({
  'tiktok' : IDL.Null,
  'youtube' : IDL.Null,
});
export const ProjectStyle = IDL.Variant({
  'social' : IDL.Null,
  'minimal' : IDL.Null,
  'cinematic' : IDL.Null,
  'threeD' : IDL.Null,
});
export const ProjectInput = IDL.Record({
  'topic' : IDL.Text,
  'goal' : ProjectGoal,
  'voiceoverType' : VoiceoverType,
  'audience' : ProjectAudience,
  'platform' : ProjectPlatform,
  'style' : ProjectStyle,
});
export const ProjectStatus = IDL.Variant({
  'scenes_ready' : IDL.Null,
  'scripted' : IDL.Null,
  'complete' : IDL.Null,
  'rendering' : IDL.Null,
  'draft' : IDL.Null,
});
export const Scene = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'voiceoverLine' : IDL.Text,
  'visualDescription' : IDL.Text,
  'index' : IDL.Nat,
});
export const Script = IDL.Record({
  'cta' : IDL.Text,
  'value' : IDL.Text,
  'patternInterrupt' : IDL.Text,
  'hook' : IDL.Text,
  'main' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProjectStatus,
  'topic' : IDL.Text,
  'owner' : IDL.Principal,
  'scenes' : IDL.Opt(IDL.Vec(Scene)),
  'goal' : ProjectGoal,
  'customScript' : IDL.Opt(IDL.Text),
  'script' : IDL.Opt(Script),
  'createdAt' : IDL.Int,
  'voiceoverType' : VoiceoverType,
  'audience' : ProjectAudience,
  'platform' : ProjectPlatform,
  'style' : ProjectStyle,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func([ProjectInput], [IDL.Nat], []),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'generateScenes' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'generateScript' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
  'getProjectCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCustomScript' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateProjectScenes' : IDL.Func([IDL.Nat, IDL.Vec(Scene)], [], []),
  'updateProjectScript' : IDL.Func([IDL.Nat, Script], [], []),
  'updateProjectStatus' : IDL.Func([IDL.Nat, ProjectStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProjectGoal = IDL.Variant({
    'educate' : IDL.Null,
    'explain' : IDL.Null,
    'sell' : IDL.Null,
    'inspire' : IDL.Null,
  });
  const VoiceoverType = IDL.Variant({ 'custom' : IDL.Null, 'auto' : IDL.Null });
  const ProjectAudience = IDL.Variant({
    'professionals' : IDL.Null,
    'students' : IDL.Null,
    'beginners' : IDL.Null,
  });
  const ProjectPlatform = IDL.Variant({
    'tiktok' : IDL.Null,
    'youtube' : IDL.Null,
  });
  const ProjectStyle = IDL.Variant({
    'social' : IDL.Null,
    'minimal' : IDL.Null,
    'cinematic' : IDL.Null,
    'threeD' : IDL.Null,
  });
  const ProjectInput = IDL.Record({
    'topic' : IDL.Text,
    'goal' : ProjectGoal,
    'voiceoverType' : VoiceoverType,
    'audience' : ProjectAudience,
    'platform' : ProjectPlatform,
    'style' : ProjectStyle,
  });
  const ProjectStatus = IDL.Variant({
    'scenes_ready' : IDL.Null,
    'scripted' : IDL.Null,
    'complete' : IDL.Null,
    'rendering' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Scene = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'voiceoverLine' : IDL.Text,
    'visualDescription' : IDL.Text,
    'index' : IDL.Nat,
  });
  const Script = IDL.Record({
    'cta' : IDL.Text,
    'value' : IDL.Text,
    'patternInterrupt' : IDL.Text,
    'hook' : IDL.Text,
    'main' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProjectStatus,
    'topic' : IDL.Text,
    'owner' : IDL.Principal,
    'scenes' : IDL.Opt(IDL.Vec(Scene)),
    'goal' : ProjectGoal,
    'customScript' : IDL.Opt(IDL.Text),
    'script' : IDL.Opt(Script),
    'createdAt' : IDL.Int,
    'voiceoverType' : VoiceoverType,
    'audience' : ProjectAudience,
    'platform' : ProjectPlatform,
    'style' : ProjectStyle,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func([ProjectInput], [IDL.Nat], []),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'generateScenes' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'generateScript' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
    'getProjectCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCustomScript' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateProjectScenes' : IDL.Func([IDL.Nat, IDL.Vec(Scene)], [], []),
    'updateProjectScript' : IDL.Func([IDL.Nat, Script], [], []),
    'updateProjectStatus' : IDL.Func([IDL.Nat, ProjectStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };