/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ProjectInput {
    topic: string;
    goal: ProjectGoal;
    voiceoverType: VoiceoverType;
    audience: ProjectAudience;
    platform: ProjectPlatform;
    style: ProjectStyle;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Script {
    cta: string;
    value: string;
    patternInterrupt: string;
    hook: string;
    main: string;
}
export interface Project {
    id: bigint;
    status: ProjectStatus;
    topic: string;
    owner: Principal;
    scenes?: Array<Scene>;
    goal: ProjectGoal;
    customScript?: string;
    script?: Script;
    createdAt: bigint;
    voiceoverType: VoiceoverType;
    audience: ProjectAudience;
    platform: ProjectPlatform;
    style: ProjectStyle;
}
export interface Scene {
    title: string;
    duration: bigint;
    voiceoverLine: string;
    visualDescription: string;
    index: bigint;
}
export interface UserProfile {
    name: string;
}
export enum ProjectAudience {
    professionals = "professionals",
    students = "students",
    beginners = "beginners"
}
export enum ProjectGoal {
    educate = "educate",
    explain = "explain",
    sell = "sell",
    inspire = "inspire"
}
export enum ProjectPlatform {
    tiktok = "tiktok",
    youtube = "youtube"
}
export enum ProjectStatus {
    scenes_ready = "scenes_ready",
    scripted = "scripted",
    complete = "complete",
    rendering = "rendering",
    draft = "draft"
}
export enum ProjectStyle {
    social = "social",
    minimal = "minimal",
    cinematic = "cinematic",
    threeD = "threeD"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VoiceoverType {
    custom = "custom",
    auto = "auto"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createProject(input: ProjectInput): Promise<bigint>;
    deleteProject(id: bigint): Promise<void>;
    generateScenes(projectId: bigint): Promise<string>;
    generateScript(projectId: bigint): Promise<string>;
    getAllProjects(): Promise<Array<Project>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getProject(id: bigint): Promise<Project>;
    getProjectCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserProjects(): Promise<Array<Project>>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateCustomScript(projectId: bigint, customScript: string): Promise<void>;
    updateProjectScenes(projectId: bigint, scenes: Array<Scene>): Promise<void>;
    updateProjectScript(projectId: bigint, script: Script): Promise<void>;
    updateProjectStatus(projectId: bigint, status: ProjectStatus): Promise<void>;
}
import type { Project as _Project, ProjectAudience as _ProjectAudience, ProjectGoal as _ProjectGoal, ProjectInput as _ProjectInput, ProjectPlatform as _ProjectPlatform, ProjectStatus as _ProjectStatus, ProjectStyle as _ProjectStyle, Scene as _Scene, Script as _Script, UserProfile as _UserProfile, UserRole as _UserRole, VoiceoverType as _VoiceoverType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProject(arg0: ProjectInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(to_candid_ProjectInput_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(to_candid_ProjectInput_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteProject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async generateScenes(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateScenes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateScenes(arg0);
            return result;
        }
    }
    async generateScript(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateScript(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateScript(arg0);
            return result;
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: bigint): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_Project_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_Project_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProjects();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProjects();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateCustomScript(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomScript(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomScript(arg0, arg1);
            return result;
        }
    }
    async updateProjectScenes(arg0: bigint, arg1: Array<Scene>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProjectScenes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProjectScenes(arg0, arg1);
            return result;
        }
    }
    async updateProjectScript(arg0: bigint, arg1: Script): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProjectScript(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProjectScript(arg0, arg1);
            return result;
        }
    }
    async updateProjectStatus(arg0: bigint, arg1: ProjectStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProjectStatus(arg0, to_candid_ProjectStatus_n36(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProjectStatus(arg0, to_candid_ProjectStatus_n36(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ProjectAudience_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectAudience): ProjectAudience {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectGoal_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectGoal): ProjectGoal {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectPlatform_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectPlatform): ProjectPlatform {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectStyle_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStyle): ProjectStyle {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_VoiceoverType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoiceoverType): VoiceoverType {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Scene>]): Array<Scene> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Script]): Script | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ProjectStatus;
    topic: string;
    owner: Principal;
    scenes: [] | [Array<_Scene>];
    goal: _ProjectGoal;
    customScript: [] | [string];
    script: [] | [_Script];
    createdAt: bigint;
    voiceoverType: _VoiceoverType;
    audience: _ProjectAudience;
    platform: _ProjectPlatform;
    style: _ProjectStyle;
}): {
    id: bigint;
    status: ProjectStatus;
    topic: string;
    owner: Principal;
    scenes?: Array<Scene>;
    goal: ProjectGoal;
    customScript?: string;
    script?: Script;
    createdAt: bigint;
    voiceoverType: VoiceoverType;
    audience: ProjectAudience;
    platform: ProjectPlatform;
    style: ProjectStyle;
} {
    return {
        id: value.id,
        status: from_candid_ProjectStatus_n18(_uploadFile, _downloadFile, value.status),
        topic: value.topic,
        owner: value.owner,
        scenes: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.scenes)),
        goal: from_candid_ProjectGoal_n21(_uploadFile, _downloadFile, value.goal),
        customScript: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.customScript)),
        script: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.script)),
        createdAt: value.createdAt,
        voiceoverType: from_candid_VoiceoverType_n25(_uploadFile, _downloadFile, value.voiceoverType),
        audience: from_candid_ProjectAudience_n27(_uploadFile, _downloadFile, value.audience),
        platform: from_candid_ProjectPlatform_n29(_uploadFile, _downloadFile, value.platform),
        style: from_candid_ProjectStyle_n31(_uploadFile, _downloadFile, value.style)
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scenes_ready: null;
} | {
    scripted: null;
} | {
    complete: null;
} | {
    rendering: null;
} | {
    draft: null;
}): ProjectStatus {
    return "scenes_ready" in value ? ProjectStatus.scenes_ready : "scripted" in value ? ProjectStatus.scripted : "complete" in value ? ProjectStatus.complete : "rendering" in value ? ProjectStatus.rendering : "draft" in value ? ProjectStatus.draft : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    educate: null;
} | {
    explain: null;
} | {
    sell: null;
} | {
    inspire: null;
}): ProjectGoal {
    return "educate" in value ? ProjectGoal.educate : "explain" in value ? ProjectGoal.explain : "sell" in value ? ProjectGoal.sell : "inspire" in value ? ProjectGoal.inspire : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    custom: null;
} | {
    auto: null;
}): VoiceoverType {
    return "custom" in value ? VoiceoverType.custom : "auto" in value ? VoiceoverType.auto : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    professionals: null;
} | {
    students: null;
} | {
    beginners: null;
}): ProjectAudience {
    return "professionals" in value ? ProjectAudience.professionals : "students" in value ? ProjectAudience.students : "beginners" in value ? ProjectAudience.beginners : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tiktok: null;
} | {
    youtube: null;
}): ProjectPlatform {
    return "tiktok" in value ? ProjectPlatform.tiktok : "youtube" in value ? ProjectPlatform.youtube : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    social: null;
} | {
    minimal: null;
} | {
    cinematic: null;
} | {
    threeD: null;
}): ProjectStyle {
    return "social" in value ? ProjectStyle.social : "minimal" in value ? ProjectStyle.minimal : "cinematic" in value ? ProjectStyle.cinematic : "threeD" in value ? ProjectStyle.threeD : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n16(_uploadFile, _downloadFile, x));
}
function to_candid_ProjectAudience_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectAudience): _ProjectAudience {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectGoal_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectGoal): _ProjectGoal {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectInput): _ProjectInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectPlatform_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectPlatform): _ProjectPlatform {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): _ProjectStatus {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectStyle_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStyle): _ProjectStyle {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_VoiceoverType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VoiceoverType): _VoiceoverType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topic: string;
    goal: ProjectGoal;
    voiceoverType: VoiceoverType;
    audience: ProjectAudience;
    platform: ProjectPlatform;
    style: ProjectStyle;
}): {
    topic: string;
    goal: _ProjectGoal;
    voiceoverType: _VoiceoverType;
    audience: _ProjectAudience;
    platform: _ProjectPlatform;
    style: _ProjectStyle;
} {
    return {
        topic: value.topic,
        goal: to_candid_ProjectGoal_n5(_uploadFile, _downloadFile, value.goal),
        voiceoverType: to_candid_VoiceoverType_n7(_uploadFile, _downloadFile, value.voiceoverType),
        audience: to_candid_ProjectAudience_n9(_uploadFile, _downloadFile, value.audience),
        platform: to_candid_ProjectPlatform_n11(_uploadFile, _downloadFile, value.platform),
        style: to_candid_ProjectStyle_n13(_uploadFile, _downloadFile, value.style)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectAudience): {
    professionals: null;
} | {
    students: null;
} | {
    beginners: null;
} {
    return value == ProjectAudience.professionals ? {
        professionals: null
    } : value == ProjectAudience.students ? {
        students: null
    } : value == ProjectAudience.beginners ? {
        beginners: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectPlatform): {
    tiktok: null;
} | {
    youtube: null;
} {
    return value == ProjectPlatform.tiktok ? {
        tiktok: null
    } : value == ProjectPlatform.youtube ? {
        youtube: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStyle): {
    social: null;
} | {
    minimal: null;
} | {
    cinematic: null;
} | {
    threeD: null;
} {
    return value == ProjectStyle.social ? {
        social: null
    } : value == ProjectStyle.minimal ? {
        minimal: null
    } : value == ProjectStyle.cinematic ? {
        cinematic: null
    } : value == ProjectStyle.threeD ? {
        threeD: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): {
    scenes_ready: null;
} | {
    scripted: null;
} | {
    complete: null;
} | {
    rendering: null;
} | {
    draft: null;
} {
    return value == ProjectStatus.scenes_ready ? {
        scenes_ready: null
    } : value == ProjectStatus.scripted ? {
        scripted: null
    } : value == ProjectStatus.complete ? {
        complete: null
    } : value == ProjectStatus.rendering ? {
        rendering: null
    } : value == ProjectStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectGoal): {
    educate: null;
} | {
    explain: null;
} | {
    sell: null;
} | {
    inspire: null;
} {
    return value == ProjectGoal.educate ? {
        educate: null
    } : value == ProjectGoal.explain ? {
        explain: null
    } : value == ProjectGoal.sell ? {
        sell: null
    } : value == ProjectGoal.inspire ? {
        inspire: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VoiceoverType): {
    custom: null;
} | {
    auto: null;
} {
    return value == VoiceoverType.custom ? {
        custom: null
    } : value == VoiceoverType.auto ? {
        auto: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
